[default]
timeout = 180

[store]
title = "네이버 공연 live beta ─ 후원유료"
url = "https://live.naver.com/store"
entrySelector = "//html/body/div[1]/div[4]/div/div[2]/div/ul/li"
titleSelector = "//div[1]/div[2]/a/text()"
linkSelector = "//div[1]/div[2]/a"
contentSelector = "//div[1]/div[2]/p[1]"
waitUntil = "networkidle"
