[fashion]
title = "코스모폴리탄 코리아 ─ 패션"
url = "https://www.cosmopolitan.co.kr/fashion"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "div.textbox em a"
linkSelector = "div.textbox em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.articlebox"
onFail = "stale"
