[default]
timeout = 180

[interpark]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitForSelector = "td[class='subject']"
onFail = "stale"
