[default]
timeout = 180

[store]
title = "네이버 공연 live beta ─ 후원유료"
url = "https://live.naver.com/store"
entrySelector = "ul.list-item li.item"
titleSelector = "a.detail-title"
linkSelector = "a.detail-title"
contentSelector = "p.date.ico-before"
waitUntil = "networkidle"
