[default]
timeout = 180

[ticket_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div.ticketListBox > div.list > div.item"
titleSelector = "a > div.row > div.col.infoWrap > p.label"
linkSelector = "a"
contentSelector = "a > div:nth-child(2) > div > dl.ticketOpen > dd"
waitForSelector = "div.list > div.item"
onFail = "stale"
